#variable keeps our codes more organised...
#They are container...
greeting = "Hello"#Here greeting is a container which stores Hello...
greeting2 = input("Ur name?:")#Here variable stores what user submits...
print(greeting +" "+greeting2)